displayName=Specific Object Hider
author=Baerog
description=Hides all interaction options for specific object instances
tags=hider,object,menu,swap
version=1.01
plugins=com.SpecificObjectHider.SpecificObjectHiderPlugin
build=standard